import { getSupabaseServerClient } from '@/lib/supabase-server';
import type { Metadata } from 'next';

export const metadata: Metadata = { title: 'Axiom Report' };

export default async function ReportPage({
  params,
}: {
  params: Promise<{ token: string }>;
}) {
  const { token } = await params;
  const supabase = await getSupabaseServerClient();
  const { data: report } = await supabase.rpc('get_shared_report', { token });

  if (!report) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <div className="text-center">
          <span className="material-symbols-outlined text-5xl text-muted-foreground block mb-3">description</span>
          <h1 className="text-lg font-bold text-foreground mb-2">Report Not Found</h1>
          <p className="text-sm text-muted-foreground">This report link is invalid or has expired.</p>
        </div>
      </div>
    );
  }

  const data = report.report_data as any;
  const summary = data?.summary;
  const details = (data?.details || []) as any[];

  return (
    <div className="min-h-screen bg-background p-8">
      <div className="max-w-4xl mx-auto">
        <div className="mb-8 text-center">
          <div className="flex items-center justify-center gap-3 mb-2">
            <div className="w-10 h-10 bg-primary rounded-lg flex items-center justify-center">
              <span className="material-symbols-outlined text-primary-foreground text-xl" style={{fontVariationSettings: "'FILL' 1"}}>terminal</span>
            </div>
            <h1 className="text-lg font-black text-foreground uppercase tracking-tighter">Axiom Report</h1>
          </div>
          <h2 className="text-xl font-extrabold text-foreground mt-4">{report.name}</h2>
          <p className="text-xs text-muted-foreground mt-1">{new Date(report.created_at).toLocaleString()}</p>
        </div>

        {summary && (
          <div className="grid grid-cols-2 md:grid-cols-5 gap-4 mb-8">
            <StatCard label="Requests" value={summary.totalRequests} />
            <StatCard label="Passed" value={summary.passedRequests} color="#10B981" />
            <StatCard label="Failed" value={summary.failedRequests} color="#EF4444" />
            <StatCard label="Duration" value={`${(summary.totalDurationMs / 1000).toFixed(1)}s`} />
            <StatCard label="Success Rate" value={`${summary.successRate?.toFixed(1) ?? 0}%`} color={summary.successRate >= 100 ? '#10B981' : '#F59E0B'} />
          </div>
        )}

        {details.length > 0 && (
          <div>
            <h3 className="text-sm font-bold text-foreground mb-4">Execution Details</h3>
            <div className="space-y-3">
              {details.map((d: any, i: number) => {
                const step = d.step || {};
                const req = d.request || {};
                const isSuccess = !step.error && step.status_code >= 200 && step.status_code < 300;
                return (
                  <div key={i} className="bg-card border border-border rounded-lg p-4">
                    <div className="flex items-center gap-3 mb-2">
                      <span className="text-[10px] font-bold px-2 py-0.5 rounded bg-primary/10 text-primary">{req.method || 'GET'}</span>
                      <span className="text-sm text-foreground font-medium">{req.name || `Request ${i + 1}`}</span>
                      <span className={`material-symbols-outlined text-sm ml-auto ${isSuccess ? 'text-[#10B981]' : 'text-[#EF4444]'}`}>
                        {isSuccess ? 'check_circle' : 'error'}
                      </span>
                    </div>
                    <div className="flex gap-4 text-xs text-muted-foreground">
                      <span>Status: {step.status_code ?? 'N/A'}</span>
                      <span>Latency: {step.latency_ms ?? 0}ms</span>
                    </div>
                    {step.error && (
                      <div className="mt-2 p-2 bg-[rgba(239,68,68,0.1)] border border-[rgba(239,68,68,0.2)] rounded text-xs text-[#FCA5A5]">{step.error}</div>
                    )}
                  </div>
                );
              })}
            </div>
          </div>
        )}

        <div className="mt-12 pt-8 border-t border-border text-center">
          <p className="text-[10px] text-muted-foreground font-mono">Generated by Axiom — API Testing & QA Platform</p>
        </div>
      </div>
    </div>
  );
}

function StatCard({ label, value, color }: { label: string; value: number | string; color?: string }) {
  return (
    <div className="bg-card border border-border p-4 rounded-lg text-center">
      <p className="text-xl font-bold font-mono" style={{ color: color || '#e4e1ed' }}>{value}</p>
      <p className="text-[10px] text-muted-foreground uppercase font-semibold mt-1">{label}</p>
    </div>
  );
}
